const Message = {
    SUCCESS: 'Operation successful',
    FAILURE: 'Operation failed',
    UNAUTHORIZED_USER: 'Unauthorized access detected',
    INVALID_KEY: 'Invalid API key provided',
    AGENT_SIGNUP_MESSAGE: 'A signup link has been successfully sent to the provided email address',
    AGENCY_SIGNUP_SUCCESS: 'Agency signup completed successfully',
    APPLICATION_ALREADY_SHARED: 'This application is already shared with another customer. Please use the same customer email or try with a new application',
    CANNOT_MOVE_BACK: 'Sorry, but you cannot move back to the previous state',
    USER_SIGN_SUCCESSFUL: 'User sign-up successful',
    USER_SAME_PLATFORM_EXIST: 'User with the same platform already exists',
    USER_WITH_THIS_PLATFORM_NOT_EXIST: 'User with this platform does not exist. Please register',
    USER_NOT_EXIST: 'User not found',
    PRODUCT_IS_NOT_ASSOCIATED_WITH_SELECTED_STATE: 'Product is not associated with selected state',
    NOT_EXIST: 'Record not found',
    NO_RECORD_FOUND: 'No records found',
    CARRIERS_DONT_EXIST_FOR_MGA: 'Carriers not connected with this MGA',
    ACCOUNT_LOCKED: 'Account deactivated',
    INVALID_CREDS: 'Invalid email or password',
    INVALID_PASSWORD: 'Incorrect password',
    INVALID_PARAMS: 'Invalid parameters provided',
    EMAIL_NOT_EXIST: 'This email does not exist in our system',
    INVALID_USER_ROLE: 'This userRole is not allowed to login',
    EMAIL_EXIST: 'User already exists with this email',
    USER_SAVED_SUCCESSFULLY: 'User saved successfully',
    USER_UPDATED_SUCCESSFULLY: 'User updated successfully',
    COMPANY_SAVED_SUCCESSFULLY: (companyType) => `${companyType} saved successfully`,
    COMPANY_UPDATED_SUCCESSFULLY: (companyType) => `${companyType} updated successfully`,
    PRODUCT_SAVED_SUCCESSFULLY: 'Product saved successfully',
    PRODUCT_UPDATED_SUCCESSFULLY: 'Product updated successfully',
    PRODUCT_EXIST: 'This product already exists in our system',
    PRODUCT_NOT_EXIST: 'This product does not exist in our system',
    PRODUCT_NOT_EXIST_WITH_SLUG: (slug) => `This product does not exist in our system with the slug ${slug}`,
    APP_TEMPLATE_NOT_EXIST: 'Application template does not exist for the selected state',
    DOMAIN_NOT_IN_LIST: 'This domain is not in the list',
    DOMAIN_INCORRECT: 'This domain does not match with the company in our system',
    BUSINESS_TYPE_INCORRECT: 'Incorrect business type',
    USER_ROLE_INCORRECT: 'Incorrect user role',
    DOMAIN_ALREADY_IN_LIST: 'Company already exists',
    SQ_DOMAIN_EXIST: 'Cannot create a domain for SquareRisk',
    PRODUCT_COMPANY_ALREADY_MAPPED: (businessType) => `It seems like this ${businessType} is already authorized with this company`,
    PRODUCT_COMPANY_NOT_EXIST: 'It seems like this product is not authorized with this company',
    PRODUCT_COMPANY_DETAIL_NOT_EXIST: 'It seems like this record does not exist',
    PAYER_COMPANY_NOT_EXIST: 'Payer company does not exist in our system',
    COMPANY_NOT_EXIST: 'Company does not exist in our system',
    ADMITTED_NON_ADMITTED_CANNOT_HAVE_SAME_STATE: 'Admitted and non-admitted cannot have common states.',
    PLEASE_TRY_DIFFERENT_PRODUCT_STATE_COMB: 'PLEASE_TRY_DIFFERENT_PRODUCT_STATE_COMBINATION',
    RECEIVER_COMPANY_NOT_EXIST: 'Receiver company does not exist in our system',
    CARRIER_COMPANY_NOT_EXIST: 'Carrier company does not exist in our system',
    PRODUCT_COMMISSION_ALREADY_MAPPED: 'It seems like this commission is already added in the system',
    PRODUCT_COMMISSION_NOT_MAPPED: 'It seems like this commission is not mapped in the system',
    PRODUCT_COMMISSION_NOT_EXIST: 'No commission found in the system',
    PRODUCT_COMMISSION_ALREADY_MAPPED_WITH_DATES: 'Commission is already added in the system with the same dates for this product',
    PRODUCT_COMMISSION_SAVED: 'Commission for the product saved successfully',
    PRODUCT_COMMISSION_UPDATED: 'Commission for the product updated successfully',
    PROPOSAL_TEMPLATE_SAVED: 'Proposal Template for the product and company saved successfully',
    PROPOSAL_TEMPLATE_UPDATED: 'Proposal Template for the product and company updated successfully',
    PROPOSAL_TEMPLATE_ALREADY_MAPPED: 'Proposal Template is already added in the system with the same company for this product',
    PROPOSAL_TEMPLATE_NOT_EXIST: 'No Proposal Template found in the system',
    AGENCY_AUTHORISED_WITH_PRODUCT: (businessType) => `${businessType} authorized with the product successfully`,
    SOMETHING_WENT_WRONG: 'Something went wrong',
    CARRIER_ALREADY_MAPPED: 'Carrier already mapped with MGA and product',
    TOO_MANY_REQUEST: (time, calls) => `More than ${calls} requests not allowed in ${time} minutes`,
    NO_PAYMENT_METHOD_OPTIONS_FOUND: 'No payment method options found',
    CARRIER_NAME_NOT_MATCH: (carrierName) => `Carrier name does not match with the incoming quote name (${carrierName})`,
    INVALID_SLUG_MENTIONED: 'Invalid Slug mentioned',
    UNAUTHORIZED_ACCESS: 'Unauthorized access',
    UNAUTHORIZED_OPERATION: 'Unauthorized Operation',
    COMMON_STATES_FOUND: (commonStates) => `${commonStates} common state(s) found in another application templates. Please change states`,
    INDICATION_COMMON_FORM_FOUND: 'common kind of form already exist',
    INDICATION_CARRIER_FORM_FOUND: 'indication kind of form already exist',
    QUOTE_CARRIER_FORM_FOUND: 'FINAL kind of form already exist',
    APPLICATION_ALREADY_EXIST: 'Application already exists',
    APPLICATION_ALREADY_BOUND: 'Application already bound',
    APPLICATION_NOT_EDITABLE: 'Application is not editable now',
    COMPANY_ALREADY_EXIST: 'Company already exists',
    RATING_SYSTEM_EXIST: 'Algorithm name with the same Product and company exists in the system',
    DATA_COLLECT_SUCCESSFUL: 'Data saved successfully',
    CHECK_WEBHOOK_UPDATES: 'Please check further updates on webhook',
    PROPOSAL_UPDATED_SUCCESSFULLY: 'Proposal updated successfully',
    APPLICATION_STATUS_SAVED: 'Application status saved',
    SUBMISSION_ID_INVALID: 'Invalid submissionResponseId field',
    NO_MGA_FOUND_FOR_GIVEN_PRODUCT: 'No MGA found for the selected product',
    SELECTED_PRODUCT_NOT_AVAILABLE_IN_THIS_STATE: '<strong>Product is not available</strong> in the selected state. Try a different Product - State combination',
    NO_COMMISION_FOUND_FOR_SELECTED_PRODUCT: 'No commission found for the selected product',
    INVALID_PAYMENT_AMOUNT: 'Invalid payment amount',
    SUBMISSION_RESPONSE_NOT_FOUND: 'Submission response not found',
    WAITING_FOR_QUOTE: 'Waiting for quote (400)',
    WAITING_FOR_SIGNATURE_PROCESS_COMPLETION: 'Waiting for signature process completion',
    QUOTE_ALREADY_BOUND: 'Quote already bound',
    QUOTES_NOT_FOUND: 'No quotes found',
    USER_WITH_DIFFERENT_ROLE_EXIST: 'It seems like this user already exists with another role. Please use a different email',
    SEND_TO_NEW_CUSTOMER: ({ productName, url, agentName, companyRole }) => `Hello,
    I have initiated your application for ${productName}. Please click on the link below to complete your application: 
    ${url}
     \n\n\n\
    Thank You,
    ${agentName}, 
    ${companyRole}.
    `,
    APPLICATION_NOT_EXIST: 'Application not exist',
    APPLICATION_APPROVE_REJECT: 'It seems like this application is already Approved OR Rejected',
    APPLICATION_SUBJECT_LINE: (productName) => `Your Application ${productName}`,
    EMAIL_TRACKER_ERROR: 'Email tracker error! Something went wrong with the email tracker',
    INVALID_APP_URL: 'It seems like this URL is not valid or expired',
    INVALID_URL: 'It seems like this URL is not valid',
    NO_ACTIONID_OR_REQUESTID_FOUND_FOR_ZOHO: 'NO request or action id found for Zoho signature',
    PLEASE_FIRST_BIND_THE_QUOTE: 'Please first bind one quote to get the sign URL',
    EMAIL_SUBJECTS: {
      PRE_REFER_MGA: (applicationId) => `Referral - SquareRisk - ${applicationId}`,
      POLICY_UPLOAD_REQUEST: (applicationId) => `Request for uploading policy for application ${applicationId}`
    },
    TASK_ALREADY_EXIST_FOR_THIS_MGA: 'Task already exists for the given MGA',
    INVALID_APPLICATION_ID: 'Invalid application Id',
    EMAIL_SEND_ERROR: 'It seems like there is some issue with sending email',
    ERROR_WHILE_SENDING_PAYMENT_FAILURE_EMAIL: 'Error while sending payment failure email',
    INSUFFICIENT_INFORMATION: 'Insufficient information',
    INDUSTRY_NOT_ELIGIBLE: 'Industry is not eligible',
    QUOTE_NOT_ELIGIBLE_FOR_USER: 'You are not eligible for this quote',
    RISK_LEVEL_HIGH: 'Risk level is too high',
    OTHERS: 'Others',
    AGENT_NOT_ASSOCIATED_WITH_APP: 'Agent is not associated with this application',
    MGA_NEED_MORE_INFO_SUBJECT: ({ applicationId, mgaName }) => `${mgaName} MGA needs more information on application ${applicationId}`,
    TOKEN_ALREADY_EXIST: 'Token already exists, please close the popup and try again',
    CANNOT_LOGIN_WITH_THIS_ROLE: 'Sorry, cannot login with this role for now',
    COMPONENT_URL_NOT_FOUND: 'URL not found in description',
    NO_MGA_TASK_ASSIGNED_TO_THE_GIVEN_MGA: ({ applicationId, mgaName }) => `No MGA task assigned to the given MGA: ${mgaName} for application ${applicationId}`,
    CARRIER_LOGO_NOT_FOUND: 'Carrier logo not found',
    QUOTE_ACCEPTED: 'Quote has been accepted successfully',
    QUOTE_REJECTED: 'Quote has been rejected successfully',
    QUOTE_REVIEW: 'Please review the quote before proceeding',
    AGENCY_UPDATE_SUCCESS: 'Agency updated successfully',
    CARRIER_RETRIEVAL_ERROR: 'Error retrieving carrier data',
    QUOTE_REVIEW_STATUS: 'Quote review status updated successfully',
    ERROR_GETTING_PREMIUM: 'Error occurred while fetching the premium',
    UNABLE_TO_PROCESS_APPLICATION: 'Unable to process application. Please try again later.',
    INVALID_DOCUMENT_TYPE: 'Invalid document type',
    DOCUMENT_NOT_UPLOADED: 'Document not uploaded',
    APPLICATION_REVIEW_STATUS: 'Application review status updated successfully',
    CARRIER_QUOTES_RETRIEVAL_ERROR: 'Error retrieving carrier quotes',
    SLOW_RESPONSE: 'Slow response from server, please try again later',
    INVALID_PROMOTION_CODE: 'Invalid promotion code',
    SUCCESSFUL_PROMOTION: 'Promotion applied successfully',
    SERVER_ERROR: 'Server encountered an error',
    INVALID_EMAIL_FORMAT: 'Invalid email format',
    REQUIRED_FIELDS_MISSING: 'Required fields are missing',
    ERROR_FETCHING_DOCUMENTS: 'Error fetching documents',
    APPLICATION_PENDING: 'Application is currently pending',
    CARRIER_CONNECTION_FAILED: 'Failed to connect with carrier',
    APPLICATION_APPROVED: 'Application has been approved',
    INVALID_STATE: 'Invalid state provided',
    VALIDATION_SUCCESS: 'Validation successful',
    PAYMENT_SUCCESSFUL: 'Payment processed successfully',
    QUOTE_BIND_SUCCESS: 'Quote has been successfully bound',
    ERROR_FETCHING_PAYMENT_INFO: 'Error fetching payment information',
    DOCUMENT_REVIEW_STATUS: 'Document review status updated successfully',
    QUOTE_PENDING: 'Quote is pending',
    INVALID_CARRIER_SELECTED: 'Invalid carrier selected',
    DATABASE_CONNECTION_FAILED: 'Database connection failed',
    APPLICATION_SUBMISSION_SUCCESS: 'Application submitted successfully',
    DOCUMENT_APPROVAL_PENDING: 'Document approval is pending',
    CARRIER_DISCONNECTED: 'Carrier has been disconnected',
    APPLICATION_STATUS_UPDATED: 'Application status has been updated',
    INSUFFICIENT_FUNDS: 'Insufficient funds for payment',
    NO_USER_ROLE_FOUND: 'No user role found for this account',
    USER_ACCOUNT_DEACTIVATED: 'User account has been deactivated',
    INVALID_PAYMENT_METHOD: 'Invalid payment method selected',
    APPLICATION_NOT_FOUND: 'Application not found',
    PAYMENT_FAILED: 'Payment has failed',
    USER_ACCOUNT_ALREADY_EXISTS: 'User account with this email already exists',
    EMAIL_ALREADY_REGISTERED: 'Email is already registered',
    USERNAME_ALREADY_TAKEN: 'Username is already taken',
    ACCOUNT_CREATION_SUCCESS: 'Account created successfully',
    PASSWORD_RESET_LINK_SENT: 'Password reset link has been sent',
    PASSWORD_RESET_SUCCESS: 'Password reset successful',
    USER_LOGOUT_SUCCESS: 'User logged out successfully',
    PROFILE_UPDATE_SUCCESS: 'Profile updated successfully',
    USER_ACCOUNT_UPDATED: 'User account updated successfully',
    USER_ACCOUNT_DELETION_SUCCESS: 'User account deleted successfully',
    EMAIL_VERIFICATION_SUCCESS: 'Email verified successfully',
    INVALID_TOKEN: 'Invalid token provided',
    UNAUTHORIZED_ACTION: 'You are not authorized to perform this action',
    INVALID_FILE_FORMAT: 'Invalid file format',
    UPLOAD_SUCCESSFUL: 'File uploaded successfully',
    UPLOAD_FAILED: 'File upload failed',
    USER_REGISTERED: 'User has been registered successfully',
    SIGNUP_SUCCESSFUL: 'Signup successful',
    SIGNUP_FAILED: 'Signup failed',
    LOGIN_SUCCESSFUL: 'Login successful',
    LOGIN_FAILED: 'Login failed',
    ACCOUNT_VERIFICATION_PENDING: 'Account verification is pending',
    ACCOUNT_VERIFICATION_SUCCESS: 'Account verification successful',
    ACCOUNT_VERIFICATION_FAILED: 'Account verification failed',
    PASSWORD_CHANGE_SUCCESS: 'Password changed successfully',
    PASSWORD_CHANGE_FAILED: 'Password change failed',
    PROFILE_PICTURE_UPDATE_SUCCESS: 'Profile picture updated successfully',
    PROFILE_PICTURE_UPDATE_FAILED: 'Profile picture update failed',
    NOTIFICATION_SENT: 'Notification sent successfully',
    NOTIFICATION_FAILED: 'Notification sending failed',
    API_CALL_SUCCESS: 'API call was successful',
    API_CALL_FAILED: 'API call failed',
    DATA_RETRIEVAL_SUCCESS: 'Data retrieved successfully',
    DATA_RETRIEVAL_FAILED: 'Data retrieval failed',
    SETTINGS_UPDATE_SUCCESS: 'Settings updated successfully',
    SETTINGS_UPDATE_FAILED: 'Settings update failed',
    SYSTEM_ERROR: 'A system error occurred',
    SYSTEM_MAINTENANCE: 'The system is currently under maintenance',
    CURRENCY_CONVERSION_SUCCESS: 'Currency converted successfully',
    CURRENCY_CONVERSION_FAILED: 'Currency conversion failed',
    RESOURCE_NOT_FOUND: 'The requested resource was not found',
    FORBIDDEN_ACCESS: 'You do not have permission to access this resource',
    SERVICE_UNAVAILABLE: 'The service is currently unavailable',
    TIMEOUT_ERROR: 'The request has timed out',
    UNEXPECTED_ERROR: 'An unexpected error has occurred',
    USER_SUSPENDED: 'User account has been suspended',
    EMAIL_NOTIFICATION_SENT: 'Email notification sent successfully',
    EMAIL_NOTIFICATION_FAILED: 'Email notification sending failed',
    PASSWORD_TOO_WEAK: 'Password is too weak',
    PASSWORD_MISMATCH: 'Passwords do not match',
    SESSION_EXPIRED: 'Your session has expired. Please log in again',
    MAINTENANCE_MODE: 'The system is in maintenance mode',
    RESET_PASSWORD_EMAIL_SENT: 'Reset password email sent successfully',
    CARRIER_NOT_AUTHORIZED: 'Carrier not authorized',
    CARRIER_AUTHORIZATION_PENDING: 'Carrier authorization is pending',
    CARRIER_AUTHORIZATION_SUCCESS: 'Carrier authorization successful',
    CARRIER_AUTHORIZATION_FAILED: 'Carrier authorization failed',
    USER_NOT_FOUND: 'User not found',
    USER_ALREADY_ACTIVE: 'User account is already active',
    TOKEN_EXPIRED: 'Token has expired',
    TOKEN_INVALID: 'Token is invalid',
    ACCOUNT_DELETION_PENDING: 'Account deletion is pending',
    ACCOUNT_DELETION_SUCCESS: 'Account deletion successful',
    ACCOUNT_DELETION_FAILED: 'Account deletion failed',
    DUPLICATE_RECORD: 'Duplicate record found',
    RECORD_CREATED_SUCCESSFULLY: 'Record created successfully',
    RECORD_UPDATED_SUCCESSFULLY: 'Record updated successfully',
    RECORD_DELETED_SUCCESSFULLY: 'Record deleted successfully',
    RECORD_NOT_FOUND: 'Record not found',
    DATABASE_ERROR: 'Database error occurred',
    FILE_NOT_FOUND: 'File not found',
    FILE_DELETION_SUCCESS: 'File deleted successfully',
    FILE_DELETION_FAILED: 'File deletion failed',
    FILE_UPLOAD_SUCCESS: 'File uploaded successfully',
    FILE_UPLOAD_FAILED: 'File upload failed',
    EMAIL_SENT_SUCCESSFULLY: 'Email sent successfully',
    EMAIL_SEND_FAILED: 'Email sending failed',
    OTP_VERIFICATION_SUCCESS: 'OTP verification successful',
    OTP_VERIFICATION_FAILED: 'OTP verification failed',
    USERNAME_NOT_FOUND: 'Username not found',
    USERNAME_ALREADY_EXISTS: 'Username already exists',
    USER_PROFILE_UPDATED: 'User profile updated successfully',
    USER_PROFILE_UPDATE_FAILED: 'User profile update failed',
    USER_ACCESS_DENIED: 'User access denied',
    REQUEST_SUCCESSFUL: 'Request was successful',
    REQUEST_FAILED: 'Request failed',
    OTP_SENT: 'OTP sent successfully',
    OTP_NOT_SENT: 'OTP not sent',
    OTP_EXPIRED: 'OTP has expired',
    OTP_INVALID: 'Invalid OTP',
    LOGIN_REQUIRED: 'Login is required to access this resource',
    AUTHENTICATION_REQUIRED: 'Authentication is required',
    USER_ACCOUNT_LOCKED: 'User account is locked',
    USER_ACCOUNT_DISABLED: 'User account is disabled',
    AUTHORIZATION_FAILED: 'Authorization failed',
    ACTION_SUCCESSFUL: 'Action completed successfully',
    ACTION_FAILED: 'Action failed',
    PROFILE_NOT_FOUND: 'Profile not found',
    SETTINGS_NOT_FOUND: 'Settings not found',
    TOKEN_REQUIRED: 'Token is required',
    DATABASE_CONNECTION_ERROR: 'Database connection error',
    SERVICE_ERROR: 'Service error occurred',
    DATA_VALIDATION_FAILED: 'Data validation failed',
    INVALID_CREDENTIALS: 'Invalid credentials provided',
    UNAUTHORIZED: 'Unauthorized',
    FORBIDDEN: 'Forbidden',
    NOT_FOUND: 'Not found',
    CONFLICT: 'Conflict',
    UNSUPPORTED_MEDIA_TYPE: 'Unsupported media type',
    INTERNAL_SERVER_ERROR: 'Internal server error',
    BAD_REQUEST: 'Bad request',
  };
  
  export default Message;
  